### ISSUE TITLE
DB Downsize and Monitor CPU usage

### ISSUE THREAD

**Issue by brm273** [indabamusic/indabamusic.github.com#4]
DB // Monitor, Converse launching around June 4th. If it doesn't impact CPU usage significantly, could 1/2 and continue to monitor.

**Comment by brm273** [comment]
Hey Andreas I don't have the correct permissions to do this. Can we check the Usage of the database instance to see if we could cut it in 1/2? Also Remove 1 Lafaro instance.

**Comment by zachfeldman** [comment]
Hey guys! Once again mind removing me from this repo?
